# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-04 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tambola', '0003_auto_20161204_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='x1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='x2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='x3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='x4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='x5',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='x6',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='x7',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='x8',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='x9',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='y1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='y2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='y3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='y4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='y5',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='y6',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='y7',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='y8',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='y9',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='z1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='z2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='z3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='z4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='z5',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='z6',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='z7',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='z8',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='z9',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticketsgenerated',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tambola.Players'),
        ),
        migrations.AlterField(
            model_name='ticketsstatus',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tambola.Players'),
        ),
        migrations.AlterField(
            model_name='winners',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tambola.Players'),
        ),
    ]
