# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-04 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tambola', '0004_auto_20161204_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsgenerated',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tambola.Players'),
        ),
        migrations.AlterField(
            model_name='ticketsstatus',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tambola.Players'),
        ),
        migrations.AlterField(
            model_name='tokensgenerated',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='winners',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='winners',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tambola.Players'),
        ),
    ]
